# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|
    config.vm.define "cent-01" do |config|
    config.vm.hostname = "cent-01"
    #config.vm.network "public_network", bridge: "br0", ip: "192.168.0.1", hostname: true
    config.vm.network "private_network", ip: "192.168.0.2"
    config.vm.box = "centos/7"
    config.vm.box_check_update = false
    config.vm.provider :libvirt do |v|
	v.memory = 1024
	end
    end
end
